#!/bin/sh

#########################
# jobscript for CUDA job
#########################
#!/bin/bash -l
#SBATCH --job-name=cuda-toolkit
#SBATCH -p gpu
#SBATCH --time=05:00:00
#SBATCH --output=cuda-test-out-%j.log
#SBATCH --gres gpu:1
# default mem is 7900M
#SBATCH --mem 30000M

module add nvidia-cuda
module add apps/python3

#Watch hardware usage
nvidia-smi


#Go back one folder to that all other paths work
cd ..


python3 train.py
