#!/bin/sh

#########################
# jobscript for CUDA job
#########################
#!/bin/bash -l
#SBATCH --job-name=Tr_LRIR
#SBATCH -p gpu
#SBATCH --time=16:00:00
#SBATCH --output=Tr_LRIR-%j.log
#SBATCH --gres gpu:1
#SBATCH --mem 30000M
#SBATCH -w gpu02
module add nvidia-cuda
module add apps/python3

#Watch hardware usage
nvidia-smi

cd ..
echo $@
python3 train.py $@

# cd Kelvin
#Set it up to rest right away
python3 test.py $@