#!/bin/sh

#########################
# jobscript for CUDA job
#########################
#!/bin/bash -l
#SBATCH --job-name=Te_LRIR
#SBATCH -p gpu
#SBATCH --time=18:00:00
#SBATCH --output=Te_LRIR-%j.log
#SBATCH --gres gpu:1
#SBATCH --mem 20000M
#SBATCH -w gpu02
module add nvidia-cuda
module add apps/python3

#Watch hardware usage
nvidia-smi


#Go back one folder to that all other paths work
cd ..

echo $@
python3 test.py $@
